export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const EDIT_CUSTOMER = "EDIT_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"

export type GET_LIST_CUSTOMER = typeof GET_LIST_CUSTOMER
export type ADD_CUSTOMER = typeof ADD_CUSTOMER
export type EDIT_CUSTOMER = typeof EDIT_CUSTOMER
export type DELETE_CUSTOMER = typeof DELETE_CUSTOMER