export const LOGIN = "LOGIN"
export const GET_INFO_CUSTOMER = "GET_INFO_CUSTOMER"
export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER"
export const GET_LIST_CUSTOMER_REGISTER = "GET_LIST_CUSTOMER_REGISTER"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const EDIT_STATUS = "EDIT_STATUS"
export const EDIT_DATE = "EDIT_DATE"
export const EDIT_NO_ACCOUNT = "EDIT_NO_ACCOUNT"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"
export const DELETE_CUSTOMER_REGISTER = "DELETE_CUSTOMER_REGISTER"

export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export type LOGIN = typeof LOGIN
export type GET_INFO_CUSTOMER = typeof GET_INFO_CUSTOMER
export type GET_LIST_CUSTOMER = typeof GET_LIST_CUSTOMER
export type GET_LIST_CUSTOMER_REGISTER = typeof GET_LIST_CUSTOMER_REGISTER
export type ADD_CUSTOMER = typeof ADD_CUSTOMER
export type EDIT_STATUS = typeof EDIT_STATUS
export type EDIT_DATE = typeof EDIT_DATE
export type EDIT_NO_ACCOUNT = typeof EDIT_NO_ACCOUNT
export type DELETE_CUSTOMER = typeof DELETE_CUSTOMER
export type DELETE_CUSTOMER_REGISTER = typeof DELETE_CUSTOMER_REGISTER

export type ALERT_SUCCESS = typeof ALERT_SUCCESS
export type ALERT_ERROR = typeof ALERT_ERROR
export type SHOW_LOADING = typeof SHOW_LOADING
export type HIDE_LOADING = typeof HIDE_LOADING